apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-skt-user05
spec:
  template:
    spec:
      containers:
      - name: app-skt-user05
        resources:
          limits:
            memory: 1Gi
